//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
namespace EntityFrameworkApp
{
    using System;
    //using System.Collections.Generic;

    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.Products = new HashSet<Product>();
        }

        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string Description { get; set; }
        public byte[] Picture { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }

    }
}



//public class Ulke
//{
//    public int UlkeID { get; set; }
//    public ICollection<Sehir> Sehilerler { get; set; }
//}




//public class Sehir
//{
//    public int SehirID { get; set; }

//    public ICollection<Ilce> Ilceler { get; set; }
//    public int UlkeID { get; set; }
//    public Ulke Ulke { get; set; }
//}
//public class Ilce
//{
//    public int IlceID { get; set; } 
//    public ICollection<Mahalle> Mahalleler { get; set; }

//    public int SehirID { get; set; }
//    public Sehir Sehir { get; set; }
//}
//public class Mahalle
//{
//    public int MahalleID { get; set; }

//    public int IlceID { get; set; }
//    public Ilce Ilce { get; set; }
//}


